### ISSUE TITLE
don't show share visualizations for measures that are averages

### ISSUE THREAD

**Issue by davelandry** [Datawheel/datawheel-canon#114]
so that means no:
- [ ] tree maps
- [ ] pie charts
- [ ] donuts

**Comment by cnavarreteliz** [comment]
That problem was solved previously,

[Definition logic aggregationType](https://github.com/Datawheel/datawheel-canon/blob/vizbuilder-0.1/packages/vizbuilder/src/components/AreaChart.jsx#L104-L109)

[Check if aggregatorType is Average](https://github.com/Datawheel/datawheel-canon/blob/vizbuilder-0.1/packages/vizbuilder/src/components/AreaChart.jsx#L149)

We need to define in annotations `annotations: { aggregation_method: "AVERAGE" }` in measures.
