### ISSUE TITLE
Retrieve current location path on server side

### ISSUE THREAD

**Issue by palamago** [Datawheel/datawheel-canon#15]
We need the equivalent of window.location.href but in server side.
React-router hasn't it on its object.

**Comment by davelandry** [comment]
I've added in some rudimentary location detection on the server side, based on what I could easily grab from the request headers. This is (in the next release) being passed through the Redux store under the "location" key:

```js
{ 
  host: 'localhost:3300',
  hostname: 'localhost',
  pathname: '/profile/040AF00182?key=value',
  port: '3300',
  query: {key: 'value'} 
}
```

@palamago I wasn't able to generate the full "href" string, which includes the `http://`, because I wasn't able to detect whether it's `http` or `https`. Let me know if you NEED that bit of the location and I'll reopen this issue to dig deeper.

**Comment by palamago** [comment]
Awesome! @davelandry thanks.
Eventually, yes, we will need the protocol (http o https). But we can start with this to create the language switch.
Is there any `req.connection.encrypted` (boolean) like express req object?

**Comment by davelandry** [comment]
yesssss @palamago that works perfectly. I'm coming to you for express knowledge now ;-)

here's what the object will now look like:
```js
{ 
  host: 'localhost:3300',
  hostname: 'localhost',
  href: 'http://localhost:3300/profile/040AF00182?key=value',
  origin: 'http://localhost:3300',
  pathname: '/profile/040AF00182',
  port: '3300',
  protocol: 'http:',
  query: {key: 'value'},
  search: '?key=value' 
}
```
