### ISSUE TITLE
i18nKey's no longer picked up by locales script

### ISSUE THREAD

**Issue by jspeis** [Datawheel/datawheel-canon#28]
i18nKey's on `<Interpolate>` tags no longer seem to get picked up with `npm run locales` ... could be related to this 8311415e91a0d0efed738e96c10f988b0a11a29a change?

**Comment by davelandry** [comment]
Yes, this is probably related to that change. I think moving forward we should just use the `t( )` function, as it actually does accept variables. The only reason I recommended the `<Interpolate>` tag in the first place was because I thought we needed it for variables, but I recently discovered that this works:

```js
t("Hello {{name}}", {name: "Jonathan"})
```

@jspeis I leave it up to you to either switch over to the t function and close this issue, or push back and tell me to make the `<Interpolate>` tag work. 😏

**Comment by jspeis** [comment]
As long as `t()` works, thats fine with me!
