### ISSUE TITLE
add "preneed" call for shared variables required for needs

### ISSUE THREAD

**Issue by jspeis** [Datawheel/datawheel-canon#8]
add "preneed" call for shared variables required for needs. these variables would be commonly used across several components and could be included along with the route parameters for each need.

**Comment by davelandry** [comment]
This one was a doozy:
 - there are now both "preneed" and "postneed" hooks for components
 - the fetchData action now uses the API environment variable (I think this was hardcoded to Data Africa?)
 - the fetchData action accepts an additional 3rd argument, a custom data formatter for the JSON result (defaults to datafold). This callback is helpful when trying to extract specific data from the result to be used in a need or postneed API query...
 - ...because now, any URL string you pass to the fetchData action will be parsed with Regex for keys in angle brackets (much like `<id>` in the past), and those keys will be swapped out for values in the URL, the data store, and then the regular store (in that order, stopping when it finds a match).

I know that's a lot, and I need to document it better, but for now here's an example usage: https://github.com/Datawheel/datawheel-canon/blob/master/app/pages/Profile.jsx#L45-L54
(check out the use of `topCrop` in particular)
